import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Inter, Libre_Caslon_Text, Lato } from 'next/font/google'

const newFont = Lato({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={newFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
